details:
  namespace: student127-bookinfo-prd
  image: ghcr.io/pizzahuhthp9/bookinfo-details
  tag: prd
  replicas: 1
  imagePullSecrets: registry-bookinfo
  port: 9080
  healthCheckPath: "/health"
ingress:
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/rewrite-target: /$2
  host: bookinfo.opsta.net
  path: "/student127/details(/|$)(.*)"
  serviceType: ClusterIP