apiVersion: v1
description: Bookinfo Ratings Service Helm Chart
name: bookinfo-details
version: 1.0.0
appVersion: 1.0.0
home: https://bookinfo.dev.opsta.net/student127/details
maintainers:
  - name: student127
    email: devop127@mail.kmutt.ac.th
sources:
  - https://github.com/pizzahuhthp9/bookinfo-details